// Code generated by internal/cmd/genversion; DO NOT EDIT.

package opus

// Public module version generated from VERSION.
const (
	Version      = "1.3.0"
	VersionMajor = 1
	VersionMinor = 3
	VersionPatch = 0
)
