// Code generated by internal/cmd/genversion; DO NOT EDIT.

package opus

// Public module version generated from VERSION.
const (
	Version      = "1.1.1"
	VersionMajor = 1
	VersionMinor = 1
	VersionPatch = 1
)
