package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
)

func main() {
	versionPath := flag.String("version", "VERSION", "path to the version source")
	outputPath := flag.String("out", "version_gen.go", "path to the generated Go file")
	flag.Parse()

	raw, err := os.ReadFile(*versionPath)
	if err != nil {
		fatalf("read version: %v", err)
	}
	version, numbers, err := parseVersion(string(raw))
	if err != nil {
		fatalf("invalid version: %v", err)
	}

	source := fmt.Sprintf(`// Code generated by internal/cmd/genversion; DO NOT EDIT.

package opus

// Public module version generated from VERSION.
const (
	Version      = %q
	VersionMajor = %d
	VersionMinor = %d
	VersionPatch = %d
)
`, version, numbers[0], numbers[1], numbers[2])
	formatted, err := format.Source([]byte(source))
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		fatalf("write generated source: %v", err)
	}
}

func parseVersion(raw string) (string, [3]int, error) {
	version := strings.TrimSpace(raw)
	parts := strings.Split(version, ".")
	if len(parts) != 3 {
		return "", [3]int{}, fmt.Errorf("%q must use major.minor.patch format", version)
	}

	var numbers [3]int
	for i, part := range parts {
		if part == "" || (len(part) > 1 && part[0] == '0') {
			return "", [3]int{}, fmt.Errorf("component %q is not a canonical non-negative integer", part)
		}
		number, err := strconv.Atoi(part)
		if err != nil || number < 0 || strconv.Itoa(number) != part {
			return "", [3]int{}, fmt.Errorf("component %q is not a canonical non-negative integer", part)
		}
		numbers[i] = number
	}
	return version, numbers, nil
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genversion: "+format+"\n", args...)
	os.Exit(1)
}
