package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
)

func main() {
	versionPath := flag.String("version", "VERSION", "path to the version source")
	outputPath := flag.String("out", "version_gen.go", "path to the generated Go file")
	flag.Parse()

	raw, err := os.ReadFile(*versionPath)
	if err != nil {
		fatalf("read version: %v", err)
	}
	version := strings.TrimSpace(string(raw))
	parts := strings.Split(version, ".")
	if len(parts) != 3 {
		fatalf("version %q must use major.minor.patch format", version)
	}
	numbers := make([]int, 3)
	for i, part := range parts {
		numbers[i], err = strconv.Atoi(part)
		if err != nil || numbers[i] < 0 {
			fatalf("version component %q is not a non-negative integer", part)
		}
	}

	source := fmt.Sprintf(`// Code generated by internal/cmd/genversion; DO NOT EDIT.

package opus

// Public module version generated from VERSION.
const (
	Version      = %q
	VersionMajor = %d
	VersionMinor = %d
	VersionPatch = %d
)
`, version, numbers[0], numbers[1], numbers[2])
	formatted, err := format.Source([]byte(source))
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		fatalf("write generated source: %v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genversion: "+format+"\n", args...)
	os.Exit(1)
}
