package silk

import (
	"fmt"
	"os"

	"github.com/darui3018823/opus/internal/entcode"
)

var lbrrDebug = os.Getenv("OPUS_LBRR_DEBUG") != ""

// leakFingerprint summarises the encoder state that influences the regular
// encode of subsequent frames, for debugging LBRR-generation state isolation.
func (e *Encoder) leakFingerprint() string {
	sum := func(xs []int32) int64 {
		var s int64
		for _, v := range xs {
			s += int64(v)
		}
		return s
	}
	return fmt.Sprintf("pPitch=%d pLagIx=%d pGainQ16=%d pGainIdx=%d pSig=%d pLagPitch=%d ffar=%v ltpSum=%d harm=%.4f tilt=%.4f lpc=%d ltp=%d xq=%d sLTP=%d nsqGain=%d ltpCorr=%.5f lagPrev=%d ltpBuf=%d shpBuf=%d lfar=%d diff=%d sLPC=%d sAR2=%d rewhite=%v curLag=%d curCont=%d nsqSeed=%d pGains=%.4f",
		e.prevPitchLag, e.prevLagIndex, e.prevGainQ16, e.prevGainIdx, e.prevSignalType, e.prevLagForPitch,
		e.firstFrameAfterReset, e.ltpSumLogGainQ7, e.shapeHarmSmooth, e.shapeTiltSmooth,
		sum(e.lpcState), sum(e.ltpState), sum32to64(e.nsq.xq), sum(e.nsq.sLTPShpQ14), e.nsq.prevGainQ16, e.ltpCorrState,
		e.nsq.lagPrev, e.nsq.sLTPBufIdx, e.nsq.sLTPShpBufIdx, e.nsq.sLFARShpQ14, e.nsq.sDiffShpQ14,
		sum(e.nsq.sLPCQ14[:]), sum(e.nsq.sAR2Q14[:]), e.nsq.rewhiteFlag,
		e.curPitchLagIndex, e.curPitchContourIndex, e.nsqSeed, sumFloats(e.prevGains))
}

func sum32to64(xs []int16) int64 {
	var s int64
	for _, v := range xs {
		s += int64(v)
	}
	return s
}

func sumFloats(xs []float64) float64 {
	var s float64
	for _, v := range xs {
		s += v
	}
	return s
}

// Inband Low Bitrate Redundancy (LBRR / in-band FEC) for the SILK encoder.
//
// LBRR carries a coarse, independently-decodable copy of an earlier frame so a
// decoder can reconstruct it via its decode_fec path after the original packet
// is lost. This mirrors libopus' SILK design (silk_LBRR_encode_FLP +
// enc_API.c): each frame, while it is regularly encoded, is *also* re-quantized
// at a lower bitrate (gains bumped up) and buffered. The buffered redundancy is
// then written at the front of the *next* packet — the one-packet FEC delay.
//
// This file contains the encoder-side buffering and replay path. Decoder-side
// LBRR extraction is implemented in decoder.go.

// lbrrSpeechActivityThresQ8 is SILK_FIX_CONST(LBRR_SPEECH_ACTIVITY_THRES, 8)
// (tuning_parameters.h: 0.3): LBRR is only coded for frames whose
// speech_activity_Q8 exceeds it.
const lbrrSpeechActivityThresQ8 = 76

// lbrrFrameData is the buffered side information + excitation of one LBRR frame
// (libopus indices_LBRR[i] / pulses_LBRR[i]), captured from the regular encode
// and replayed into the next packet.
type lbrrFrameData struct {
	present         bool // LBRR_flags[i]
	condIndependent bool // first frame of an LBRR run (gain index bumped)
	signalType      int
	quantOffset     int

	// gainSymbols are the GainsIndices as coded: the regular frame's symbols
	// with GainsIndices[0] raised by LBRR_GainIncreases at a run start.
	gainSymbols []int

	nlsf nlsfAnalysis

	// Voiced-only pitch/LTP indices (copied from the regular frame).
	lagIndex      int
	contour       int
	ltpPerIdx     int
	ltpGainIdx    []int
	ltpScaleIndex int

	seed   int32
	pulses []int16
}

// SetInbandFEC enables or disables SILK inband FEC (LBRR). When enabled and the
// per-frame speech activity is high enough, each packet carries a redundant
// copy of the previous packet's frame(s). Default: disabled.
func (e *Encoder) SetInbandFEC(enabled bool) {
	e.lbrrEnabled = enabled
	if !enabled {
		e.pendingLBRR = nil
		e.curLBRR = nil
		e.pendingLBRRFrames = 0
		e.pendingLBRRStereoPred = nil
	}
	if e.side != nil {
		e.side.SetInbandFEC(enabled)
	}
}

// SetLBRRCoded sets LBRR_coded for the next packet (the Opus layer's
// decide_fec result). Unlike SetInbandFEC(false) it keeps the redundant frames
// generated by the previous packet, which silk_Encode still emits.
func (e *Encoder) SetLBRRCoded(coded bool) {
	e.lbrrEnabled = coded
	if e.side != nil {
		e.side.lbrrEnabled = coded
	}
}

// SetPacketLossPerc sets the expected packet-loss percentage (0..100). It feeds
// the LBRR gain-increase schedule (more loss → smaller, cheaper LBRR frames).
func (e *Encoder) SetPacketLossPerc(perc int) {
	if perc < 0 {
		perc = 0
	}
	if perc > 100 {
		perc = 100
	}
	e.packetLossPerc = perc
	if e.side != nil {
		e.side.packetLossPerc = perc
	}
}

// setupLBRR mirrors silk_setup_LBRR (silk_control_encoder, run once per
// packet): LBRR_GainIncreases is 7 when LBRR was not enabled for the previous
// packet (which was therefore coded at a higher rate), otherwise
// max(7 - PacketLoss_perc * 0.2, 3).
func (e *Encoder) setupLBRR() {
	prev := e.lbrrEnabledPrev
	e.lbrrEnabledPrev = e.lbrrEnabled
	if !e.lbrrEnabled {
		return
	}
	if !prev {
		e.lbrrGainIncreases = 7
		return
	}
	g := 7 - int(silkSMULWB(int32(e.packetLossPerc), int16(13107))) // SILK_FIX_CONST(0.2, 16)
	if g < 3 {
		g = 3
	}
	e.lbrrGainIncreases = g
}

// beginLBRRPacket resets the per-packet LBRR accumulation state.
func (e *Encoder) beginLBRRPacket() {
	e.curLBRR = e.curLBRR[:0]
}

// finishLBRRPacket promotes the LBRR frames generated for the just-encoded
// packet to "pending", so they are emitted at the front of the next packet.
func (e *Encoder) finishLBRRPacket(nFrames int) {
	any := false
	for i := range e.curLBRR {
		if e.curLBRR[i].present {
			any = true
			break
		}
	}
	if any {
		e.pendingLBRR = append([]lbrrFrameData(nil), e.curLBRR...)
		e.pendingLBRRFrames = nFrames
	} else {
		e.pendingLBRR = nil
		e.pendingLBRRFrames = 0
	}
}

// silkGainsDequant ports silk_gains_dequant: ind are the coded symbols
// (absolute index for k == 0 without conditional coding, delta symbols
// otherwise), prevInd the running LastGainIndex. It returns the absolute
// index of every subframe (the gains follow from silk_log2lin as in the NSQ).
func silkGainsDequant(ind []int, prevInd *int, conditional bool, nbSubfr int) []int {
	abs := make([]int, nbSubfr)
	for k := 0; k < nbSubfr; k++ {
		if k == 0 && !conditional {
			// Gain index is not allowed to go down more than 16 steps (~21.8 dB)
			if ind[k] > *prevInd-16 {
				*prevInd = ind[k]
			} else {
				*prevInd = *prevInd - 16
			}
		} else {
			indTmp := ind[k] + MinDeltaGainQuant
			dbl := 2*MaxDeltaGainQuant - NLevelsQGain + *prevInd
			if indTmp > dbl {
				*prevInd += indTmp<<1 - dbl
			} else {
				*prevInd += indTmp
			}
		}
		*prevInd = clampInt(*prevInd, 0, NLevelsQGain-1)
		abs[k] = *prevInd
	}
	return abs
}

// generateLBRRFrame ports silk_LBRR_encode_FLP. It is called from
// encodeRangeFrame once the frame's side information is fixed and builds (but
// does not emit) the redundant copy: the regular indices with the first gain
// index raised by LBRR_GainIncreases at a run start, the gains re-derived with
// silk_gains_dequant from LBRRprevLastGainIndex, and a fresh NSQ pass from the
// pre-frame quantizer state with the regular frame's seed, shaping and Lambda.
func (e *Encoder) generateLBRRFrame(
	signal []float64,
	signalType, quantOffset int,
	gainSymbols []int,
	lastGainIndex int,
	conditional bool,
	nlsf nlsfAnalysis,
	pitchLags []int,
	ltpCoeffsQ14 [][5]int16,
	ltpScaleQ14 int16,
	frameSeed int32,
	rateScale float64,
	preFrame encoderFrameState,
) {
	if !e.lbrrEnabled {
		return
	}
	// LBRR_enabled && speech_activity_Q8 > LBRR_SPEECH_ACTIVITY_THRES. An
	// LBRR frame is always coded with the active type table, so an inactive
	// frame (never active enough in libopus either) is skipped explicitly.
	fr := lbrrFrameData{
		present:     e.speechActivityQ8 > lbrrSpeechActivityThresQ8 && signalType != SignalTypeInactive,
		signalType:  signalType,
		quantOffset: quantOffset,
	}
	if !fr.present || len(gainSymbols) != e.nSubframes {
		fr.present = false
		e.curLBRR = append(e.curLBRR, fr)
		return
	}

	fr.condIndependent = len(e.curLBRR) == 0 || !e.curLBRR[len(e.curLBRR)-1].present
	fr.gainSymbols = append([]int(nil), gainSymbols...)
	if fr.condIndependent {
		// First frame in packet or previous frame not LBRR coded.
		e.lbrrPrevLastGainIndex = lastGainIndex
		fr.gainSymbols[0] += e.lbrrGainIncreases
		if fr.gainSymbols[0] > NLevelsQGain-1 {
			fr.gainSymbols[0] = NLevelsQGain - 1
		}
	}
	// Decode to get gains in sync with the decoder.
	gAbs := silkGainsDequant(fr.gainSymbols, &e.lbrrPrevLastGainIndex, conditional, e.nSubframes)

	// Re-quantize the excitation from the pre-frame NSQ state, then restore
	// the post-frame state the regular path produced.
	saved := e.snapshotFrameState()
	savedSeed := e.nsqSeed
	e.restoreFrameState(preFrame)
	e.nsqSeed = frameSeed
	pulses := e.closedLoopNSQWithRateScale(signal, nlsf.lpcQ12, nlsf.lpcQ12Interp, gAbs,
		signalType, quantOffset, frameSeed, pitchLags, ltpCoeffsQ14, ltpScaleQ14, rateScale)
	fr.seed = e.nsqSeed
	e.restoreFrameState(saved)
	e.nsqSeed = savedSeed

	fr.pulses = append([]int16(nil), pulses...)
	fr.nlsf = nlsf
	if signalType == SignalTypeVoiced {
		fr.lagIndex = e.capLagIndex
		fr.contour = e.capContour
		fr.ltpPerIdx = e.capLTPPerIdx
		fr.ltpGainIdx = append([]int(nil), e.capLTPGainIdx...)
		fr.ltpScaleIndex = e.capLTPScaleIndex
	}
	e.curLBRR = append(e.curLBRR, fr)
}

// emitPendingLBRR writes the LBRR flag, the per-frame LBRR flags (for 2/3-frame
// packets), and the buffered LBRR frame bodies at the front of the current
// packet — immediately after the VAD flags, matching the SILK grammar. With FEC
// disabled (or no pending data) it writes a single 0 bit, identical to the prior
// hardcoded behaviour.
func (e *Encoder) emitPendingLBRR(enc *entcode.Encoder, nFrames int) (lbrrBits int) {
	symbol := e.pendingLBRRSymbol(nFrames)
	lbrrFlag := symbol > 0
	enc.EncodeBitLogp(lbrrFlag, 1)
	e.lbrrFlag = lbrrFlag
	// curr_nBitsUsedLBRR counts from after the VAD/LBRR flag placeholder.
	start := enc.ECTell()
	if !lbrrFlag {
		return 0
	}
	e.writePendingLBRRMask(enc, nFrames, symbol)

	if lbrrDebug {
		pend := e.pendingLBRR
		fmt.Fprintf(os.Stderr, "[LBRR emit] nFrames=%d symbol=%#b flag=%v\n", nFrames, symbol, lbrrFlag)
		for i := range pend {
			fmt.Fprintf(os.Stderr, "  frame %d: present=%v condIndep=%v sig=%d qoff=%d gainSyms=%v nPulses=%d seed=%d\n",
				i, pend[i].present, pend[i].condIndependent, pend[i].signalType, pend[i].quantOffset,
				pend[i].gainSymbols, len(pend[i].pulses), pend[i].seed)
		}
	}

	e.writePendingLBRRBodies(enc, symbol)
	return enc.ECTell() - start
}

func (e *Encoder) pendingLBRRSymbol(nFrames int) int {
	if len(e.pendingLBRR) != nFrames || e.pendingLBRRFrames != nFrames {
		return 0
	}
	symbol := 0
	for i := range e.pendingLBRR {
		if e.pendingLBRR[i].present {
			symbol |= 1 << uint(i)
		}
	}
	return symbol
}

// HasPendingLBRR reports whether the next packet with nFrames can carry any
// redundant frame generated by the previous packet. Stereo returns true when
// either the mid or side component has emit-ready data.
func (e *Encoder) HasPendingLBRR(nFrames int) bool {
	if e.pendingLBRRSymbol(nFrames) != 0 {
		return true
	}
	return e.side != nil && e.side.pendingLBRRSymbol(nFrames) != 0
}

// HasAnyPendingLBRR reports whether redundant data exists even if a packet
// duration change makes it impossible to emit with the requested grammar.
func (e *Encoder) HasAnyPendingLBRR() bool {
	if len(e.pendingLBRR) != 0 {
		return true
	}
	return e.side != nil && len(e.side.pendingLBRR) != 0
}

// DiscardPendingLBRR expires redundant data that cannot be represented by the
// next packet's frame-count syntax. This mirrors an active encode, which would
// replace the old pending set instead of allowing it to reappear later.
func (e *Encoder) DiscardPendingLBRR() {
	e.pendingLBRR = nil
	e.pendingLBRRFrames = 0
	e.pendingLBRRStereoPred = nil
	if e.side != nil {
		e.side.pendingLBRR = nil
		e.side.pendingLBRRFrames = 0
	}
}

func (e *Encoder) writePendingLBRRMask(enc *entcode.Encoder, nFrames, symbol int) {
	if symbol == 0 || nFrames <= 1 {
		return
	}
	if nFrames == 2 {
		enc.EncodeIcdf(symbol-1, silkLBRRFlags2ICDF[:], 8)
	} else {
		enc.EncodeIcdf(symbol-1, silkLBRRFlags3ICDF[:], 8)
	}
}

func (e *Encoder) writePendingLBRRBodies(enc *entcode.Encoder, symbol int) {
	var ec lbrrECState
	for i := range e.pendingLBRR {
		if symbol&(1<<uint(i)) == 0 {
			continue
		}
		e.writeLBRRFrame(enc, e.pendingLBRR[i], i > 0 && symbol&(1<<uint(i-1)) != 0, &ec)
	}
}

// lbrrECState carries ec_prevSignalType / ec_prevLagIndex across the LBRR
// frames of one packet (silk_encode_indices updates them for LBRR frames too;
// the following regular frame is coded independently, so they do not leak).
type lbrrECState struct {
	prevSignalType int
	prevLagIndex   int
}

func (e *Encoder) appendMissingLBRRFrame() {
	if e.lbrrEnabled {
		e.curLBRR = append(e.curLBRR, lbrrFrameData{})
	}
}

// writeLBRRFrame replays one buffered LBRR frame's side information and pulses
// into the range coder: silk_encode_indices(encode_LBRR = 1, condCoding) +
// silk_encode_pulses. condCoding is CODE_CONDITIONALLY when the previous frame
// of the packet is LBRR coded as well.
func (e *Encoder) writeLBRRFrame(enc *entcode.Encoder, fr lbrrFrameData, conditional bool, ec *lbrrECState) {
	cb := getNLSFCB(e.lpcOrder)

	// Signal type + quantizer offset (LBRR always uses the active/VAD table).
	e.encodeTypeOffset(enc, true, fr.signalType, fr.quantOffset)

	// Gains.
	if conditional {
		enc.EncodeIcdf(fr.gainSymbols[0], silkDeltaGainICDF[:], 8)
	} else {
		enc.EncodeIcdf(fr.gainSymbols[0]>>3, silkGainICDF[fr.signalType][:], 8)
		enc.EncodeIcdf(fr.gainSymbols[0]&7, silkUniform8ICDF[:], 8)
	}
	for _, sym := range fr.gainSymbols[1:] {
		enc.EncodeIcdf(sym, silkDeltaGainICDF[:], 8)
	}

	// NLSFs + interpolation factor.
	e.encodeNLSF(enc, cb, fr.signalType, fr.nlsf)
	if e.nSubframes == 4 {
		enc.EncodeIcdf(fr.nlsf.interpFactor, silkNLSFInterpFactorICDF[:], 8)
	}

	// Pitch lags + LTP (voiced only).
	if fr.signalType == SignalTypeVoiced {
		fsKHz := e.sampleRate / 1000
		encodeLagIndex(enc, fsKHz, fr.lagIndex, conditional && ec.prevSignalType == SignalTypeVoiced, ec.prevLagIndex)
		ec.prevLagIndex = fr.lagIndex
		encodePitchContour(enc, fsKHz, e.nSubframes, fr.contour)
		enc.EncodeIcdf(fr.ltpPerIdx, silkLTPPerIndexICDF[:], 8)
		for sf := 0; sf < e.nSubframes; sf++ {
			idx := 0
			if sf < len(fr.ltpGainIdx) {
				idx = fr.ltpGainIdx[sf]
			}
			switch fr.ltpPerIdx {
			case 0:
				enc.EncodeIcdf(idx, silkLTPGainICDF0[:], 8)
			case 1:
				enc.EncodeIcdf(idx, silkLTPGainICDF1[:], 8)
			default:
				enc.EncodeIcdf(idx, silkLTPGainICDF2[:], 8)
			}
		}
		if !conditional {
			enc.EncodeIcdf(fr.ltpScaleIndex, silkLTPScaleICDF[:], 8)
		}
	}
	ec.prevSignalType = fr.signalType

	// Seed + excitation.
	enc.EncodeIcdf(int(fr.seed), silkUniform4ICDF[:], 8)
	e.encodePulses(enc, fr.pulses, fr.signalType, fr.quantOffset)
}

// encodeLagIndex codes a pitch lag index like silk_encode_indices: as a delta
// (silk_pitch_delta_iCDF) when conditional coding follows a voiced frame and
// the delta lies in [-8, 11], otherwise absolutely (high bits + low bits,
// preceded by the out-of-range delta symbol 0 in the conditional case).
func encodeLagIndex(enc *entcode.Encoder, fsKHz, lagIndex int, delta bool, prevLagIndex int) {
	if delta {
		d := lagIndex - prevLagIndex
		if d >= -8 && d <= 11 {
			enc.EncodeIcdf(d+9, silkPitchDeltaICDF[:], 8)
			return
		}
		enc.EncodeIcdf(0, silkPitchDeltaICDF[:], 8)
	}
	step := fsKHz >> 1
	if step < 1 {
		step = 1
	}
	enc.EncodeIcdf(lagIndex/step, silkPitchLagICDF[:], 8)
	encodePitchLagLowBits(enc, fsKHz, lagIndex%step)
}
