package extensions

import (
	"bytes"
	"errors"
	"reflect"
	"testing"
)

func TestGenerateMatchesLibopusVector(t *testing.T) {
	exts := []Extension{
		{ID: 3, Frame: 0, Data: []byte("a")},
		{ID: 32, Frame: 10, Data: []byte("DRED")},
		{ID: 33, Frame: 1, Data: []byte("NOT DRED")},
		{ID: 4, Frame: 4},
	}
	got, err := Generate(exts, 11, 27)
	if err != nil {
		t.Fatal(err)
	}
	want := []byte{
		1, 1, 1, 1,
		3<<1 | 1, 'a',
		0x02,
		33<<1 | 1, 8, 'N', 'O', 'T', ' ', 'D', 'R', 'E', 'D',
		0x03, 3,
		4 << 1,
		0x03, 6,
		32 << 1, 'D', 'R', 'E', 'D',
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("generated bytes:\n got % x\nwant % x", got, want)
	}
}

func TestGenerateParseShortLongAndPadding(t *testing.T) {
	input := []Extension{
		{ID: 3, Frame: 0, Data: []byte{0xa1}},
		{ID: 4, Frame: 0},
		{ID: 32, Frame: 1, Data: bytes.Repeat([]byte{0x5a}, 510)},
		{ID: 127, Frame: 2, Data: []byte("tail")},
	}
	data, err := Generate(input, 3, 600)
	if err != nil {
		t.Fatal(err)
	}
	if len(data) != 600 {
		t.Fatalf("generated length = %d, want 600", len(data))
	}
	got, err := Parse(data, 3)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, input) {
		t.Fatalf("roundtrip:\n got %#v\nwant %#v", got, input)
	}
	got[0].Data[0] = 0
	if input[0].Data[0] != 0xa1 {
		t.Fatal("Parse returned aliased payload data")
	}
}

func TestGenerateUsesRepeatForSharedSequence(t *testing.T) {
	input := []Extension{
		{ID: 3, Frame: 0, Data: []byte("a")},
		{ID: 32, Frame: 0, Data: []byte("zero")},
		{ID: 3, Frame: 1, Data: []byte("b")},
		{ID: 32, Frame: 1, Data: []byte("one")},
		{ID: 3, Frame: 2, Data: []byte("c")},
		{ID: 32, Frame: 2, Data: []byte("two")},
	}
	data, err := Generate(input, 3, 0)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(data, []byte{0x04}) && !bytes.Contains(data, []byte{0x05}) {
		t.Fatalf("generated stream has no repeat indicator: % x", data)
	}
	got, err := Parse(data, 3)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, input) {
		t.Fatalf("repeat roundtrip:\n got %#v\nwant %#v\nwire % x", got, input, data)
	}
}

func TestMalformedStreams(t *testing.T) {
	tests := []struct {
		name string
		data []byte
		n    int
	}{
		{"short payload missing", []byte{3<<1 | 1}, 1},
		{"long lacing missing", []byte{32<<1 | 1}, 1},
		{"long payload truncated", []byte{32<<1 | 1, 4, 1, 2}, 1},
		{"frame increment past end", []byte{0x03, 2}, 2},
		{"separator at last frame", []byte{0x02}, 1},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := Parse(tt.data, tt.n); !errors.Is(err, ErrInvalidPacket) {
				t.Fatalf("Parse error = %v, want ErrInvalidPacket", err)
			}
		})
	}

	repeated := []Extension{
		{ID: 3, Frame: 0, Data: []byte("a")},
		{ID: 33, Frame: 1, Data: []byte("NOT DRED")},
		{ID: 4, Frame: 4},
		{ID: 32, Frame: 10, Data: []byte("DRED")},
		{ID: 32, Frame: 9, Data: []byte("DRED")},
		{ID: 4, Frame: 9, Data: []byte("b")},
		{ID: 4, Frame: 10, Data: []byte("c")},
	}
	data, err := Generate(repeated, 11, 0)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Parse(data[:len(data)-5], 11); !errors.Is(err, ErrInvalidPacket) {
		t.Fatalf("truncated repeat error = %v, want ErrInvalidPacket", err)
	}
}

func TestGenerateRejectsInvalidArguments(t *testing.T) {
	tests := []Extension{
		{ID: 2, Frame: 0},
		{ID: 128, Frame: 0},
		{ID: 3, Frame: 0, Data: []byte{1, 2}},
		{ID: 32, Frame: -1},
		{ID: 32, Frame: 1},
	}
	for _, ext := range tests {
		if _, err := Generate([]Extension{ext}, 1, 0); !errors.Is(err, ErrBadArg) {
			t.Fatalf("Generate(%+v) error = %v, want ErrBadArg", ext, err)
		}
	}
	if _, err := Generate([]Extension{{ID: 32, Frame: 0, Data: []byte("abcd")}}, 1, 2); !errors.Is(err, ErrBufferTooSmall) {
		t.Fatalf("small target error = %v, want ErrBufferTooSmall", err)
	}
}
