param(
    [string]$OutDir = "testdata/real_corpus",
    [int]$Seconds = 8
)

$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$sourceDir = Join-Path $OutDir "source"
New-Item -ItemType Directory -Force -Path $sourceDir | Out-Null

$seedUrl = "https://raw.githubusercontent.com/voxserv/audio_quality_testing_samples/master/testaudio/48000/test01_20s.wav"
$seed = Join-Path $sourceDir "cc_speech_test01_20s.wav"
if (!(Test-Path $seed)) {
    Invoke-WebRequest -UseBasicParsing -Uri $seedUrl -OutFile $seed
}

$readme = Join-Path $OutDir "README.md"
@"
# Real Corpus Seed

Generated by `scripts/fetch_real_corpus.ps1`.

Seed source:

- `voxserv/audio_quality_testing_samples`, `testaudio/48000/test01_20s.wav`
- Original recordings are described by that project as Freesound human speech
  distributed under Creative Commons licenses.

Derived clips:

- `clean_speech`: trimmed 48 kHz mono speech
- `noisy_speech`: clean speech mixed with synthetic broadband noise
- `onset_plosive`: first seconds of the clean speech seed
- `stereo_speech`: clean speech duplicated into stereo with a slight right-channel delay
- `mixed`: clean speech mixed with a quiet tonal bed
- `music`: synthetic tonal/chord fixture, included only as a non-speech anchor

Additional user-provided 16-bit PCM or float32 WAV files can be placed under any
subdirectory of this folder. The scoreboard test scans `**/*.wav`.
"@ | Set-Content -Encoding UTF8 $readme

$ffmpeg = Get-Command ffmpeg -ErrorAction SilentlyContinue
if ($null -eq $ffmpeg) {
    $cleanDir = Join-Path $OutDir "clean_speech"
    New-Item -ItemType Directory -Force -Path $cleanDir | Out-Null
    Copy-Item -Force $seed (Join-Path $cleanDir "cc_speech_48k_mono.wav")
    Write-Host "ffmpeg not found; downloaded clean speech only. Install ffmpeg for noisy/stereo/mixed/music derived clips."
    exit 0
}

function Invoke-FFmpeg($Arguments) {
    & $ffmpeg.Source @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "ffmpeg failed: $($Arguments -join ' ')"
    }
}

$clipLen = [Math]::Max(1, $Seconds)

$cleanDir = Join-Path $OutDir "clean_speech"
$noisyDir = Join-Path $OutDir "noisy_speech"
$onsetDir = Join-Path $OutDir "onset_plosive"
$stereoDir = Join-Path $OutDir "stereo_speech"
$mixedDir = Join-Path $OutDir "mixed"
$musicDir = Join-Path $OutDir "music"
@($cleanDir, $noisyDir, $onsetDir, $stereoDir, $mixedDir, $musicDir) | ForEach-Object {
    New-Item -ItemType Directory -Force -Path $_ | Out-Null
}

$clean = Join-Path $cleanDir "cc_speech_48k_mono.wav"
Invoke-FFmpeg @("-y", "-i", $seed, "-t", "$clipLen", "-ar", "48000", "-ac", "1", "-sample_fmt", "s16", $clean)

$onset = Join-Path $onsetDir "cc_speech_onset_48k_mono.wav"
Invoke-FFmpeg @("-y", "-i", $seed, "-ss", "2", "-t", "$([Math]::Min($clipLen, 4))", "-ar", "48000", "-ac", "1", "-sample_fmt", "s16", $onset)

$noisy = Join-Path $noisyDir "cc_speech_noise_48k_mono.wav"
Invoke-FFmpeg @("-y", "-i", $clean, "-f", "lavfi", "-i", "anoisesrc=color=white:amplitude=0.025:duration=${clipLen}:sample_rate=48000", "-filter_complex", "[0:a][1:a]amix=inputs=2:duration=first:normalize=0", "-ar", "48000", "-ac", "1", "-sample_fmt", "s16", $noisy)

$stereo = Join-Path $stereoDir "cc_speech_48k_stereo.wav"
Invoke-FFmpeg @("-y", "-i", $clean, "-filter_complex", "[0:a]asplit=2[l][r];[r]adelay=2S|2S[rdel];[l][rdel]join=inputs=2:channel_layout=stereo", "-ar", "48000", "-ac", "2", "-sample_fmt", "s16", $stereo)

$mixed = Join-Path $mixedDir "cc_speech_tone_mix_48k_mono.wav"
Invoke-FFmpeg @("-y", "-i", $clean, "-f", "lavfi", "-i", "sine=frequency=220:duration=${clipLen}:sample_rate=48000", "-filter_complex", "[1:a]volume=0.06[tone];[0:a][tone]amix=inputs=2:duration=first:normalize=0", "-ar", "48000", "-ac", "1", "-sample_fmt", "s16", $mixed)

$music = Join-Path $musicDir "synthetic_chords_48k_stereo.wav"
Invoke-FFmpeg @("-y", "-f", "lavfi", "-i", "sine=frequency=220:duration=${clipLen}:sample_rate=48000", "-f", "lavfi", "-i", "sine=frequency=277.18:duration=${clipLen}:sample_rate=48000", "-f", "lavfi", "-i", "sine=frequency=329.63:duration=${clipLen}:sample_rate=48000", "-filter_complex", "[0:a]volume=0.05[a0];[1:a]volume=0.04[a1];[2:a]volume=0.03[a2];[a0][a1][a2]amix=inputs=3:duration=first:normalize=0,pan=stereo|c0=c0|c1=0.7*c0", "-ar", "48000", "-ac", "2", "-sample_fmt", "s16", $music)

Write-Host "Real corpus written to $OutDir"
